services:
  web:
    build: .
    container_name: user_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: userdb
      DB_USER: root
      DB_PASSWORD: root

  db:
    image: mysql:8.0
    container_name: user_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: